version: '3.8'

services:
  explorer-sig-provider:
    image: ghcr.io/blockscout/sig-provider:${EXPLORER_DOCKER_TAG_SIG_PROVIDER:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'explorer-sig-provider'
    ports:
      - 8151:8050
