version: '3.8'

services:
  explorer-proxy:
    image: nginx:1.25.3
    container_name: explorer-proxy
    volumes:
      - "../proxy/default.conf.template:/etc/nginx/templates/default.conf.template"

  visualizer-proxy:
    image: nginx:1.25.3
    container_name: visualizer-proxy
    volumes:
      - "../proxy/visualizer.conf.template:/etc/nginx/templates/default.conf.template"
    environment:
      - NGINX_CONFIG_VERSION=1
