version: '3.8'

services:
  explorer-frontend:
    image: ghcr.io/blockscout/frontend:${EXPLORER_DOCKER_TAG_FRONTEND:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'explorer-frontend'
    env_file:
      -  ../envs/common-frontend.env
