version: '3.8'

services:
  explorer-smart-contract-verifier:
    image: ghcr.io/blockscout/smart-contract-verifier:${EXPLORER_DOCKER_TAG_SMART_CONTRACT_VERIFIER:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'explorer-smart-contract-verifier'
    env_file:
      -  ../envs/common-smart-contract-verifier.env
    ports:
      - target: 8050
        published: 8150
