version: '3.8'

services:
  explorer-stats-db:
    image: postgres:15
    restart: always
    container_name: 'explorer-stats-postgres'
    command: postgres -c 'max_connections=200'
    environment:
        POSTGRES_USER: 'explorer_stats_user'
        POSTGRES_PASSWORD: 'explorer_stats_password'
        POSTGRES_DB: 'explorer_stats_db'

  explorer-stats:
    image: ghcr.io/blockscout/stats:${EXPLORER_DOCKER_TAG_STATS:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'explorer-stats'
    env_file:
      -  ../envs/common-stats.env
    environment:
      - STATS__CREATE_DATABASE=true
      - STATS__RUN_MIGRATIONS=true
