PrivateKey = {Path = "/pk/dac-member.keystore", Password = "testonly"}

[L1]
WsURL = "ws://zkevm-mock-l1-network:8546"
RpcURL = "http://zkevm-mock-l1-network:8545"
PolygonValidiumAddress = "0x1F708C24a0D3A740cD47cC0444E9480899f3dA7D"
DataCommitteeAddress = "0x68B1D87F95878fE05B998F19b66F4baba5De1aed"
Timeout = "3m"
RetryPeriod = "5s"
BlockBatchSize = 32
TrackSequencer = true
GenesisBlock = "31"

[Log]
Environment = "development" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[DB]
User = "committee_user"
Password = "committee_password"
Name = "committee_db"
Host = "zkevm-data-node-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = 8444
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500
